enum ActionNames {
  SET_PRODUCT_ITEMS = "SET_PRODUCT_ITEMS",
  SET_FILTER_IN_LISTS = "SET_FILTER_IN_LISTS",
  SET_FILTER_IN_RANGES = "SET_FILTER_IN_RANGES",
  SET_SORT_MODE = "SET_SORT_MODE",
}

export default ActionNames;
