import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
import Container from "@mui/material/Container";
import Paper from "@mui/material/Paper";
import Box from "@mui/material/Box";

// import Container from "@mui/material/Container";
import classes from "styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Fruits and Vegetables - And Other Kitchen Wonders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="md">
        <Paper elevation={0} sx={{ border: "1px solid #ddd" }}>
          <Box>Here is the beginning</Box>
        </Paper>
      </Container>
    </>
  );
};

export default Home;
